version: '3.8'

services:
  db:
    image: postgres:16
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - dbdata:/var/lib/postgresql/data
    env_file:
      - .env.db
    networks:
      - mynetwork

  backend:
    build: .
    command: >
      bash -c "python manage.py makemigrations &&
      python manage.py migrate &&
      python create_superuser.py &&
      gunicorn transcendence.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/code
    expose:
      - 8000
    env_file:
      - .env.db
      - .env.backend
    depends_on:
      db:
       condition: service_healthy
    networks:
      - mynetwork
  
  nginx:
    build: ./nginx
    ports:
      #- "8080:80"
      - "8443:8443"
    depends_on:
      - backend
    networks:
      - mynetwork

networks:
 mynetwork:

volumes:
 dbdata:
 static_volume:
