version: '3.8'

services:
  db:
    image: postgres:16
    volumes:
      - dbdata:/var/lib/postgresql/data
    env_file:
      - .env.db
    networks:
      - mynetwork

  backend:
    build: .
    command: >
      bash -c "python manage.py makemigrations &&
      python manage.py migrate &&
      python create_superuser.py &&
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env.db
      - .env.backend
    depends_on:
      - db
    networks:
      - mynetwork

networks:
 mynetwork:

volumes:
 dbdata:
